frase = 'Curso em vídeo Python'
print(frase)
print(frase.upper())
print(frase.lower())
print(frase[0].lower())
print(frase[0:10].lower())
print(frase[9::2])
print(len(frase))
print(frase.count('o'))
print(frase.count('o', 0, 13))
print(frase.find('deo'))
print(frase.find('Android'))
print(frase.replace('Python', 'Android'))
frase_replace = frase.replace('Python', 'C')
print(frase_replace)
print(frase.capitalize())
print(frase.title())
print('Curso' in frase)
print(frase.lower().find('vídeo'))
frase_1 = '   Aprenda Python  '
print(frase_1)
print(frase_1.strip())
print(len(frase_1))
print(len(frase_1.strip()))
print(frase_1.rstrip())
print(frase_1.lstrip())
print(frase.split())
frase_split = frase.split()
print(frase_split[0])
print(frase_split[3])
print(frase_split[3][2])
print('-'.join(frase_split))
