x = input('Digite algo: ')
print('O tipo primitivo é: ', type(x))
print(f'A sequencia digitada foi {x}')
print('É só espaçoes? ', x.isspace() )
print(f'É númerico? {x.isnumeric()}')
print(f'É alfanúmerico? {x.isalnum()}')
print(f'É alfabeto? {x.isalpha()}')
print(f'É minusculo? {x.islower()}')
print(f'É imprimível? {x.isprintable()}')
print('Está capitalizada? ', x.istitle())
